name: Create PR with Template Changes
on:
  workflow_run:
    workflows: [Check for Template new Release]
    types:
      - completed
      
env:
  BRANCH_NAME: chore/merge_${{ vars.TEMPLATE_REPO }}_${{ vars.TEMPLATE_LATEST_RELEASE }}

jobs:
  on-new-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check if Template Latest Release is newer than the current based on
        id: compare_versions
        uses: fabriziocacicia/semver-compare-action@v0.1.0
        with:
          first: '${{ vars.TEMPLATE_LATEST_RELEASE }}'
          second: '${{ vars.UPDATED_TO_TEMPLATE_RELEASE }}'
          operator: '>'
      - name: "Cancel Workflow if no new Release"
        uses: potiuk/cancel-workflow-runs@v4_7
        if: ${{ !fromJSON(steps.compare_versions.outputs.result) }}
        with:
          cancelMode: self
          selfPreservation: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Config git user
        shell: bash
        run: |
          git config user.name "Merge Template Changes Workflow"
          git config user.email "<>"
      - name: Create a PR with the changes of the new release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          git remote add template https://github.com/${{ vars.TEMPLATE_REPO }}.git
          git pull template ${{ vars.TEMPLATE_LATEST_RELEASE }} --rebase --strategy=recursive -X theirs
          git push -u origin ${{ env.BRANCH_NAME }}
          gh pr create --base ${{ github.ref_name }} --head ${{ env.BRANCH_NAME }} --title "chore: merge ${{ vars.TEMPLATE_REPO }} ${{ vars.TEMPLATE_LATEST_RELEASE }} changes" --body "" 
      - name: Post Run if failed
        if: failure()
        uses: webiny/action-post-run@3.0.0
        id: post-run-command
        with:
          run: |
            git branch --delete ${{ env.BRANCH_NAME }}
            gh api --method DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ vars.TEMPLATE_REPO }}/actions/variables/TEMPLATE_LATEST_RELEASE
  on-no-new-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'skipped' || github.event.workflow_run.conclusion == 'canceled' }}
    steps:
      - run: echo 'The template has no new release'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The Check for Template new Release failed'

